site_name: Gravitate Documentation
theme:
  name: material
  font:
    text: Montserrat
  icon:
    repo: fontawesome/brands/gitlab
    icon:
      admonition:
        note: fontawesome/solid/note-sticky
        abstract: fontawesome/solid/book
        info: fontawesome/solid/circle-info
        tip: fontawesome/solid/bullhorn
        success: fontawesome/solid/check
        question: fontawesome/solid/circle-question
        warning: fontawesome/solid/triangle-exclamation
        failure: fontawesome/solid/bomb
        danger: fontawesome/solid/skull
        bug: fontawesome/solid/robot
        example: fontawesome/solid/flask
        quote: fontawesome/solid/quote-left

  features:
    - navigation.tracking
    - content.code.annotate
    - content.tabs.link
    - content.tooltips
    - navigation.expand
    - navigation.sections
  logo: assets/Logos/gravitate.png
  favicon: assets/Logos/favicon.png
  palette:
    primary: blue
plugins:
  - glightbox
extra:
  generator: false
  social:
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/gravitate
copyright: Copyright &copy; 2022 - 2023 Gravitate

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - tables
  - footnotes
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - attr_list
  - md_in_html
  - def_list
  - abbr
  - pymdownx.snippets
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
